### ISSUE TITLE
[공용] 게임 플로우에서 PlayStart 단계 추가.

### ISSUE THREAD

**Issue by LeeHyungJoo** [KKangTaee/HifeSurvival#18]
각각 클라마다 게임을 로드하는 시간이 다르다. 
그러므로, 게임 시작하는 시간을 맞추려면, 
각각 클라에서 로드를 마치고 이제 조작이 가능한 상태를 모두 체크를 해야한다. 
그래야 게임을 시작하도록 한다.

```
  <packet name ="PlayStartRequest">
    <int name ="id"/>
  </packet>
```
로드 다 끝난 후. 요청. 
```
  <packet name ="PlayStartResponse">
    <int name = "id"/>
  </packet>
```
받은 후에도 대기. (나중에 로딩바나 그럴때 이 패킷을 받는 기점으로 로딩 완료를 보여준다)

```
  <packet name ="UpdateGameModeStatusBroadcast">
    <int name ="status"/>
  </packet>
```
GameMode 에서 Status 가 바뀔 때마다 status 값을 내려준다. 

status 값은 다음과 같다. 
```
public enum GameModeStatus
{
    None,
    Ready,
    Countdown,
    LoadGame,
    PlayStart,
    FinishGame,
}
```

LoadGame 이 이 전 GameStart와 같다. 
괜찮은 값 이름이 있다면 코멘트 . 

PlayStart 가 내려가는 순간. 게임이 조작 가능토록 하면 됨.

**Comment by LeeHyungJoo** [comment]
@KKangTaee  클라 확인 대기 중

**Comment by KKangTaee** [comment]
EGameModeStatus 상태값은 다음과 같음
* Ready : 캐릭터 선택 대기
* Countdown : 모든 유저가 캐릭터 선택
* LoadGame : Countdown 종료 후, 인게임 진입
* PlayStart : 플레이어가 모두 인게임에 진입
* FinishGame : 게임 종료
