### ISSUE TITLE
[공용] 이동로직 구현

### ISSUE THREAD

**Issue by KKangTaee** [KKangTaee/HifeSurvival#2]
### 이슈내용

- 타 클라이언트의 이동이 매끄럽지 않은 이슈

### 재현스텝

1. 유저  A, B가 있을 때
2. 유저 A가 이동하게 되면 B유저의 화면에서 A의 이동에 대한 동기화가 매끄럽지 않음.
3. 마치 한, 두 프레임이 늦은 느낌? (B의 화면에서)

### 작동 원리

- 유저가 디패드를 통해 방향전환이 이루어질 때 패킷을 Send 함 (CS_Move)
- CS_Move 패킷을 서버에서 전달받게 되면 해당 오브젝트(Player)엔티티를 찾아 상태를 이동으로 변경 (MoveState)
- 이동 상태에서 특정 시간(UPDATE_TIME) 간격으로 서버에서 연산을 통해 타 클라이언트의 예측 좌표를 브로드 캐스팅을 함.
- 브로드 캐스팅으로 전달받은 이동 패킷을 바탕으로 유저의 이동을 동기화 시킴
    - 해당 유저의 현 클라이언트에 놓인 좌표와 이동 패킷으로 전달받은 좌표간의 보간처리를 함.

### 확인 해야 할 부분

1. 현재 작동원리가 올바른 원리인지 확인이 필요함
    - 그렇지 않다면..? 어떻게 변경해야하는가에 대한 논의가 필요.
2. 1번이 괜찮다면..? 그럼 동기화가 재대로 이루어지지 않는 원인이 어디?
    1. 클라이언트 이슈
    2. 서버이슈

**Comment by LeeHyungJoo** [comment]
A, B 는 모바일과 에디터로 재현했음.

**Comment by LeeHyungJoo** [comment]
현재 원리는 벡터 + 시간 값으로 이동을 처리하고 있지만, 
이런 방식으로는 로그만 봐서는 어떤 위치인지 알기 어려움. 
다시 계산해보고, 추적하는 일이 발생함. 

위와 같은 이유로, 절대 좌표를 사용해 패킷 수정과 정책을 수정하는 방향으로 진행할 예정.

**Comment by LeeHyungJoo** [comment]
<packet name ="MoveRequest">
		<int name ="targetId"/>
		<struct_PVec3 name ="currentPos"/>
		<struct_PVec3 name ="targetPos"/>
		<float name ="speed"/>
		<long name ="timestamp"/>
	</packet>

- currentPos 현재 포지션 
- targetPos 가려고 하는 포지션 (현재 포지션과 같은 값으로 보내면 멈춤)
- timestamp 움직이기 시작했을 때 시간
- 디패드 활성화 되고 있을 때, 0.25초 후에 해당 방향으로 도착할 지점을 targetPos 로 넘겨주는 방식. 

	<packet name ="PlayerUpdateBroadcast">
		<int name ="targetId"/>
		<bool name ="isPlayer"/>
		<int name ="status"/>
		<struct_PVec3 name ="currentPos"/>
		<struct_PVec3 name ="targetPos"/>
		<float name ="speed"/>
		<long name ="timestamp"/>
	</packet>

- status로 캐릭터 여러 상태를 체크할 예정. 
- 다만 현재는 Idle은 멈춤, Move 는 움직임으로 판단. 
- timestamp가 있는 이유는 클라이언트에서 보간하기 위한 값. 
- 클라가 패킷을 받았을 때, 원래 요청한 시간 값과 비교해 현재 위치를 조정함을 기대함.

**Comment by LeeHyungJoo** [comment]
서버 작업 1차 마무리.

**Comment by KKangTaee** [comment]
### 클라이언트 구현과정의 예
A클라이언트가 (0, 0) 위치에서 디패드에 입력을 받아 0.25초 후에 (0, 4) 위치로 이동한다고 했으면?
A클라이언트가 패킷을 보낸 시점이 0분 1초이고, 도착했을 때의 예측 시간은 0분 3.5초임.

만약 B클라이언트가 A패킷의 브로드캐스팅을 받은 시간이 0분 2초라고 한다면?
B클라이언트 입장에서는 0분 2초에서 시작하고 0분 3.5초 내에 (0, 4) 위치에 A클라이언트를 이동해야하니
1.5초 안에 이동을 시켜야 하는게 아닌가 라는 생각.

### 그렇다면 여기서 생각 해봐야하는 부분
1. 사실 상대방의 속력은 다른 유저의 입장에서 그리 필요하지 않는것 같음. (어차피 예측시간이 정해저 있으니)
2. A클라이언트가 디패드로 움직였는데, 앞에 충돌체가 있을때는 사실상 그쪽으로 이동하지 못함. 하지만 예측 값은 충돌체를 관통해서 좌표가 나올 수 있음 : 이 경우에는 클라이언트에서 미리 충돌을 확인하고 패킷을 안보내는 방향으로 가야하는가?
3. 위에서 멈추는 방법은 currPos와 targetPos가 일치한 경우 멈춤으로 인지된다고 했는데, 디패드가 움직이는 시점에는 무조건 0.25이후의 좌표를 반환하는데, 어떻게 currPos와 targetPos가 일치하는 상황이 발생하는가? : 이건 사실 디패드를 땐 상황이 아님?

**Comment by KKangTaee** [comment]
### 현재 구현된 상황
1. 0.25초 주기로 보내도록 MoveRequest를 하도록 구현.
2. 디패드를 땟을경우 MoveRequest에 currPos랑 targetPos를 일치한 상황에서 Send (괜찮은 방식인듯).
3. 보간 처리방식은 전송된 timestamp의 값에서 0.25를 더한 값에, 현재 클라이언트에서 Now로 찍힌 타임스탬프의 차를 기준으로. deltatime을 추가하여 보간 처리하는 방식. (MoveMachine.Co_MoveLerpExpect 메서드)

### 위의 이동방식에서 현재 발생된 이슈
A클라이언트의 디패드 입력에서 0.25초를 더한 시간보다 더 늦게 브로드 캐스팅이 내려오는 경우 움직이지 않는다...
(즉, A클라이언트가 0분 3.5초에 (0,4)에 도달하도록 만들었는데, B클라이언트에서 브로드 캐스팅을 받았을 때가 0분 4초인 경우.

이 경우에 대해 생각이 필요함.

**Comment by LeeHyungJoo** [comment]
**_2.  A클라이언트가 디패드로 움직였는데, 앞에 충돌체가 있을때는 사실상 그쪽으로 이동하지 못함. 하지만 예측 값은 충돌체를 관통해서 좌표가 나올 수 있음 : 이 경우에는 클라이언트에서 미리 충돌을 확인하고 패킷을 안보내는 방향으로 가야하는가?_**

Answer)
현재는 클라이언트에서 일단 미리 충돌 체크하는 것이 좋다고 판단. 
물론, 나중에는 맵 데이터를 서버도 들고 있으면서 2중 충돌 체크를 하는 것이 궁극적인 목표. 
그렇다면 왜 궁극적으로는 2중 체크를 할까? 

문제는 각각 클라이언트에서 여럿 모종의 이유로 맵 데이터가 서로 달랐을 경우 발생 함
어떤 클라이언트에선 이동되는데, 어떤 클라이언트에선 이동 못하는 경우를 허용해서는 안됨.
이는 명백히 버그..! 그래서 서버와 2중 체크가 필요. 
즉 이때 맵 데이터를 서버도 들고 충돌 체크를 할 수 있어야 한다. 

클라만 체크 했을 경우, 다음과 같은 경우 발생할 수 있음. 
ex)
A클라이언트 ->접속 -> 맵 데이터 로드 -> 로비에서 대기 중
-> 맵 데이터 변경.
-> B클라이언트 -> 접속 -> 바뀐 맵 데이터 로드 -> 로비에서 대기 중 
-> A,B 가 게임 진입. 
-> 클라이언트를 믿고 서로 좌표를 보내고 있는데, A와 B가 패킷 보내는게 다름(맵 데이터가 다르므로..!) 
<<버그!!>>

중요한 건 불특정 다수가 어떤 데이터를 들고 있을지 모르는 상황을 만들면 안되긴 함. 
다만, 그럴 경우를 대비하는 것. 
서버 체크를 하면, 최소 다른 데이터들을 들고 있는지 여부를 알 수 있음.


===> 결론 
a. 현재는 2중 체크는 우선 순위가 낮음.  (주의만 하면 발생 안 함. 불특정 다수가 필요한 테스트가 아님)
b. 그러므로, 현재는 클라이언트에서만 미리 충돌을 확인하고 패킷을 처리.
c. 다만, 벽에 스킬이 막히거나, 맵 데이터에 영향을 받는 다른 이슈가 생기면 "2중 체크" 우선 순위가 올라갈 수 있음

**Comment by LeeHyungJoo** [comment]
**_3. 위에서 멈추는 방법은 currPos와 targetPos가 일치한 경우 멈춤으로 인지된다고 했는데, 디패드가 움직이는 시점에는 무조건 0.25이후의 좌표를 반환하는데, 어떻게 currPos와 targetPos가 일치하는 상황이 발생하는가? : 이건 사실 디패드를 땐 상황이 아님?_**


Answer)
맞음. 얘기했듯이  멈추는 상황은 다시 논의 해봐야 함. 
다만, 현재 디패드 떼었을 때 
currentPos 와 targetPos 를 같은 값으로 서버로 보내면 
멈추는 처리하도록 했음.

**Comment by LeeHyungJoo** [comment]
**_A클라이언트가 (0, 0) 위치에서 디패드에 입력을 받아 0.25초 후에 (0, 4) 위치로 이동한다고 했으면?
A클라이언트가 패킷을 보낸 시점이 0분 1초이고, 도착했을 때의 예측 시간은 0분 3.5초임.

만약 B클라이언트가 A패킷의 브로드캐스팅을 받은 시간이 0분 2초라고 한다면?
B클라이언트 입장에서는 0분 2초에서 시작하고 0분 3.5초 내에 (0, 4) 위치에 A클라이언트를 이동해야하니
1.5초 안에 이동을 시켜야 하는게 아닌가 라는 생각._**


Answer) 설명한 것이 맞는데, 같은 생각인지 확인 요청

(0,0) (0.4) 두 개의 점을 서로 잇는 선이 있다고 가정. (움직일 경로)
s-----------------------e
i
(s는 시작점(0,0), i는 A 플레이어 위치, e는 도착점)

도착 점까지 2.5초만에 갈 예정
B에서 브로드캐스팅 받은 시간은 패킷을 쏜 시간 후 1초 경과함. 
B클라이언트에서는 A 플레이어 위치를 아래와 같이 즉시 이동 시키고 (여기서 즉시는 lerp 하게 자연스럽게 할 것인지는 재량)
s-----------------------e
          i
이후 남은 시간 1.5초 동안 기존 속도대로 도착 지점까지 가면 됨.

**Comment by LeeHyungJoo** [comment]
_**위의 이동방식에서 현재 발생된 이슈
A클라이언트의 디패드 입력에서 0.25초를 더한 시간보다 더 늦게 브로드 캐스팅이 내려오는 경우 움직이지 않는다...
(즉, A클라이언트가 0분 3.5초에 (0,4)에 도달하도록 만들었는데, B클라이언트에서 브로드 캐스팅을 받았을 때가 0분 4초인 경우.**_


Answer)
가장 현재와 가까운 시점, 즉 가장 최근에 일어난 패킷 기준으로 캐릭터 위치를 즉시 이동 시킴
마찬가지로 이걸 자연스럽게 보일려면 보간이 필요함. 

이미 지나가버린 시간대에 들어온 broadcast 패킷의 결과 값을 현재 상태로 만드는 것이 맞다고 판단.

**Comment by LeeHyungJoo** [comment]
++
서버에서 동기화 하는 경우, 어쩔 수 없이 시차가 발생하고 
이에 따라서 미세하게 맞지 않는 경우가 생길 수도 있음. 
더 정확도를 높이려면 UDP 방식을 사용해야 함. 
TCP의 한계. 
TCP를 사용하면서 해당 시차 이슈를 해결하려면, 좀 더 R&D 가 필요할 것으로 생각됨. 

다만, 현재 정확도는 어느 정도, 기능만 완성 시키는 것이 더 우선 순위가 높다고 판단.

**Comment by LeeHyungJoo** [comment]
#10 해당 이슈와 연결.
