### ISSUE TITLE
[클라] 공격하다가 간헐적으로 멈추는 현상

### ISSUE THREAD

**Issue by LeeHyungJoo** [KKangTaee/HifeSurvival#23]
NullReferenceException: Object reference not set to an instance of an object
StateMachine`1[T].ChangeState[P] (EntityObject+EStatus inStatus, T inSelf, P& inParam) (at Assets/Scripts/EntityObject/StateMachine.cs:23)
Monster.ChangeState[P] (EntityObject+EStatus inStatus, P& inParam) (at Assets/Scripts/EntityObject/Monster.cs:43)
EntityObjectController`1[T].SetIdleState (T inTarget, UnityEngine.Vector3& inCurrPos, UnityEngine.Vector3& inDir, System.Single inSpeed) (at Assets/Scripts/Controller/EntityObjectController.cs:172)
EntityObjectController`1[T].OnUpdateLocation (UpdateLocationBroadcast inPacket) (at Assets/Scripts/Controller/EntityObjectController.cs:44)
GameMode.OnUpdateLocation (UpdateLocationBroadcast inPacket) (at Assets/Scripts/Realtime/GameMode.cs:477)
ClientPacketHandler.UpdateLocationBroadcastHandler (ServerCore.Session session, IPacket packet) (at Assets/Scripts/Realtime/ClientPacketHandler.cs:83)
PacketManager.HandlePacket (ServerCore.Session inSession, IPacket inPacket) (at <0de4e371948d4a269a74ab4329a3582d>:0)
NetworkManager.Update () (at Assets/Scripts/Managers/NetworkManager.cs:54)

재현되는 조건은 모르겠음.

**Comment by KKangTaee** [comment]
해당 이슈는 Status가 초기화 되지 않은 상태에서 Update가 호출되면서 발생한 이슈임.
수정 함
