### ISSUE TITLE
[공동] 아이템 성장 시스템 구현. 

### ISSUE THREAD

**Issue by LeeHyungJoo** [KKangTaee/HifeSurvival#33]
[#24](https://github.com/KKangTaee/HifeSurvival/discussions/24#discussioncomment-6348992)

위 토론 참조.

**Comment by LeeHyungJoo** [comment]
```
<struct name = "PDropItem">
  <int name ="itemKey"/>
</struct>
```

- itemKey : 드랍될 아이템 키. 해당 키를 활용해서 notice 혹은 아이템 이미지 보이도록하는 용도

```
<struct name = "PInvenItem">
	<int name ="slot" />
	<int name ="itemKey"/>
	<int name ="str"/>
	<int name ="def"/>
	<int name ="hp"/>
	<struct_PItemSkill name ="skill" />
</struct>
```

- slot : 장착 슬롯 번호 0부터 시작. 
- itemKey : 아이템 키 
- str, def, hp : 스탯인데, 나중에 Stat 구조체로 뺄 예졍. ( Addtional Stat 용 패킷 구조체)
- skill : 스킬 구조체. (임시)

```
<struct name = "PItemSkill">
	<int name ="skillKey" />
	<int name ="sort"/>
	<int name ="coolTime"/>
</struct>
```

- skillKey : 스킬 키 
- sort : 아래 enum 값 참조. (클라 표기용) 

```
public enum ESkillSort
{
    NONE,
    DEALT,
    HEAL,
    BUFF,
    DEBUFF,
}
```

- coolTime : 쿨 타임 작업 용. 우선 임시로 내렸음. (항상 데이터용 쿨타임 내려감)

```
<packet name ="UpdateInvenItem">
	<struct_PInvenItem name ="invenItem"/>
</packet>
```

- 인벤 아이템 (장착 아이템)은 항상 이 패킷으로 관리하도록 함. 
장착, 업그레이드 등등

**Comment by KKangTaee** [comment]
[요청] @LeeHyungJoo 
* 어떤 패킷을 보내면 어떤 패킷이 내려오는지에 대한 가이드라인 정리
* 또, 어떻게 변화가 이루어지는지 설명

**Comment by LeeHyungJoo** [comment]
위에 설명한 UpdateInvenItem  패킷 하나로 
좌측에 보이는 인벤 아이템 리스트들을 갱신

Update 패킷은 어떤 패킷을 요청했을 때 받는게 아니라, 
아이템 먹는 행위 등, 특정 행위로 아이템을 갱신 해야하는 상황에 항상 내려감. 

변화가 아닌 항상 스냅샷 형태로 내려감. (현재 인벤 아이템 상태, 값들 그대로)

**Comment by KKangTaee** [comment]
맨처음 아이템 획득 시
level : 1, currentStack : 0, maxStack : 0
두번째 획득시
level : 1, currentStack : 1, maxStack : 2
* 첫 스택획득시 maxStack 값이 0이 아닌 2로 나와야 함.

**Comment by LeeHyungJoo** [comment]
@KKangTaee  위 버그 수정 함!!!
